### ISSUE TITLE
Update github templates

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool-website#12]
Templates [issue_template](https://github.com/ESMValGroup/ESMValTool-website/blob/main/.github/issue_template.md) and [pull_request_template](https://github.com/ESMValGroup/ESMValTool-website/blob/main/.github/pull_request_template.md) should be updated, removing information related to `beautiful-jekyll`

**Comment by axel-lauer** [comment]
First go at updating the GitHub templates: #32
