### ISSUE TITLE
Updating ESMValTool gallery

### ISSUE THREAD

**Issue by TomasTorsvik** [ESMValGroup/ESMValTool-website#14]
Please only submit feature suggestions or bug reports if you believe something is broken.

If you need help, or if you enjoy Beautiful Jekyll and want to support it, please upgrade to one of our plans: https://beautifuljekyll.com/plans/

**Comment by TomasTorsvik** [comment]
At the moment there are (at least) 3 "gallery" pages related to ESMValTool:
- The [ESMValtool website gallery](https://esmvaltool.org/gallery/)
- The [ESMValTool docs gallery](https://docs.esmvaltool.org/en/latest/gallery.html)
- The [ESMValTool latest release gallery](https://esmvaltool.dkrz.de/shared/esmvaltool/stable_release/)

Can we coordinate these galleries better in some way?

**Comment by axel-lauer** [comment]
Is it fine to close this issue now that the branch has been merged?

**Comment by TomasTorsvik** [comment]
Yes, it's fine. I was wondering if there would be any more comments about the different galleries, but it's not ugent in any way. Closing the issue now.
