### ISSUE TITLE
Out of date link to website on GitHub repository

### ISSUE THREAD

**Issue by bsolino** [ESMValGroup/ESMValTool-website#20]
On the right panel of the GitHub repository it still shows the old link to the website (https://esmvalgroup.github.io/ESMValTool-website) instead of the shorter new link (https://esmvaltool.org/).

![image](https://github.com/ESMValGroup/ESMValTool-website/assets/20075170/ab710986-670c-49fd-b3ab-3f13e5736cb7)

**Comment by axel-lauer** [comment]
Thanks! Done.
